In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Đọc tập dữ liệu rược vang trắng

In [ ]:
import pandas as pd

# cau 1a
wine_white = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", delimiter=";")
df_wine_white = pd.DataFrame(wine_white)
print(wine_white)

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.0              0.27         0.36  ...       0.45      8.8        6
1               6.3              0.30         0.34  ...       0.49      9.5        6
2               8.1              0.28         0.40  ...       0.44     10.1        6
3               7.2              0.23         0.32  ...       0.40      9.9        6
4               7.2              0.23         0.32  ...       0.40      9.9        6
...             ...               ...          ...  ...        ...      ...      ...
4893            6.2              0.21         0.29  ...       0.50     11.2        6
4894            6.6              0.32         0.36  ...       0.46      9.6        5
4895            6.5              0.24         0.19  ...       0.46      9.4        6
4896            5.5              0.29         0.30  ...       0.38     12.8        7
4897            6.0              0.21         0.38  ...       0.3

### Kiễm tra giá trị của datasets

In [ ]:
#cau 1b
print(wine_white.shape[0]) # co 4898 phan tu

4898


In [ ]:
print(len(set(wine_white.iloc[:,-1]))) # co 7 gia tri nhan khac nhau

7


### Huấn luyện datasets theo nghi thức Hold-out

In [ ]:
# cau 1c
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df_wine_white.drop(columns=['quality']),df_wine_white.iloc[:,-1], test_size = 2/10.0, random_state=100)

print(len(x_test)) # So luong phan tu trong tap test = 980

print(len(x_train)) # So luong phan tu trong tap hoc = 3918


980
3918


### Sử dụng Cây quyết định để huấn luyện mô hình

In [ ]:
#cau 1d
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = "entropy", random_state=100)
model.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

### Dự đoán nhãn

In [ ]:
#cau 1e
# Du doan nhan
y_pred = model.predict(x_test)
print(y_pred)

### Đánh giá độ chính xác của mô hình

In [ ]:
from sklearn.metrics import accuracy_score
print("Do chinh xac tap kiem tra ", accuracy_score(y_test,y_pred)*100)

Do chinh xac tap kiem tra  61.73469387755102


### Đánh giá độ chính xác tổng thể bằng ma trận Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
import numpy as np
a = np.unique(wine_white.quality)
print("Do chinh xac tong the ")
print(confusion_matrix(y_test, y_pred, a)) 

Do chinh xac tong the 
[[  0   1   1   3   1   0   0]
 [  1   9   6   8   2   0   0]
 [  1  13 175  76  14   1   0]
 [  1   8  81 301  53   8   0]
 [  0   1  10  57 103   6   1]
 [  0   1   2   8   8  17   0]
 [  0   1   0   0   1   0   0]]


### Dự đoán nhãn cho 10 phần tử đầu

In [ ]:
# cau 1f
# Du doan nhan cho 10 phan tu dau tien
y_pred10 = model.predict(x_test[0:10])

print(list(y_test[0:10])) # Nhan thuc te cua 10 phan tu dau la: [7, 5, 6, 6, 6, 6, 6, 6, 6, 6]
print(y_pred10) # Nhan du doan cho 10 phan tu dau la: [7 5 5 6 7 5 6 5 6 6]

[7, 5, 6, 6, 6, 6, 6, 6, 6, 6]


In [ ]:
print("Do chinh xac tap kiem tra 10 phan tu dau ", accuracy_score(y_test[0:10],y_pred10)*100) # = 60.0

Do chinh xac tap kiem tra 10 phan tu dau  60.0


In [ ]:
print("Do chinh xac tong the cho 10 phan tu dau ")
print(confusion_matrix(y_test[0:10], y_pred10, a))

Do chinh xac tong the cho 10 phan tu dau 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 3 4 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


### Tạo tập dữ liệu dữ đoán giới tính


In [ ]:
# Cau 2:
X = [[180, 15, 0],[167, 42, 1],[136, 35, 1],[174, 15, 0],[141, 28, 1]]
# 0 = Nam, 1 = Nu
Y = [0, 1, 1, 0, 1]

In [ ]:
columns_X = ["Chieu cao","Do dai mai toc","Giong noi"]
X_df = pd.DataFrame(X, columns=columns_X)
columns_Y = ["Gioi tinh"]
Y_df = pd.DataFrame(Y, columns=columns_Y)
print(X_df)
print(Y_df)

   Chieu cao  Do dai mai toc  Giong noi
0        180              15          0
1        167              42          1
2        136              35          1
3        174              15          0
4        141              28          1
   Gioi tinh
0          0
1          1
2          1
3          0
4          1


In [ ]:
model_2 = DecisionTreeClassifier(criterion = "entropy")
model_2.fit(X, Y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
print(model_2.predict([[130, 38, 1]])) # ket qua = 1 la Nu

[1]
